[package]
name = "browser-engine"
version = "0.1.0"
authors = ["justincremer <jacremer@live.com>"]
edition = "2018"

[dependencies]
gfx = "0.14.0"
gfx_text = "0.15.0"
gfx_window_glutin = "0.14.0"
glutin = "0.7.1"
